package org.dkb.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;

@Entity
@Table(name = "shortened_url", indexes = {
        @Index(name = "idx_short_code", columnList = "shortCode", unique = true)
})
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ShortenedUrl {

    /**
     * Primary key. ID generated by DB
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Original URL provided by user.
     */
    @Column(name = "long_url", nullable = false, unique = true, length = 2048)
    private String longUrl;

    /**
     * Unique shortCode (es. "aBcD1eF").
     */
    @Column(name = "short_code", unique = true, length = 8)
    private String shortCode;

    /**
     * Date and time of creation of the record.
     */
    @CreationTimestamp
    private Instant createdAt;
}